# Generated by Django 5.1.5 on 2025-01-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_friendrequest_userprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
